# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 3

